### ISSUE TITLE
Error loading ammo.wasm.js

### ISSUE THREAD

**Issue by prolightHub** [yandeu/enable3d#4]
Am I loading something wrong or is this repository broken?
Here's the error:
enable3d@0.0.14.min.js:105 Uncaught Error: failed to load /lib/ammo.wasm.js at HTMLScriptElement.QM.n.onerror

QM.n.onerror @ enable3d@0.0.14.min.js:105
error (async)
QM @ enable3d@0.0.14.min.js:105
$M @ enable3d@0.0.14.min.js:105
(anonymous) @ enable3d@0.0.14.min.js:105
setTimeout (async)
aT @ enable3d@0.0.14.min.js:105
(anonymous) @ index.js:363
load (async)
window.addEventListener @ cordova.js:140
(anonymous) @ index.js:362

**Comment by yandeu** [comment]
Ammo is the physics engine. It is lazy loaded from the /lib/ folder. Make sure all 3 ammo files are inside that folder.

I also noticed that you are using cordova? Maybe WebAssembly code does not run well on cordova. Normally the loader can tell if WebAssembly is available or not and will load the right version.

Maybe you should try to load the JavaScript version of ammo instead? I have not implemented to force load a specific version of ammo yet. Maybe try to delete ammo.wasm.js and then rename ammo.js to ammo.wasm.js? This way it will hopefully only load the JavaScript version.

**Comment by prolightHub** [comment]
Where do I place the /lib/ folder?

**Comment by prolightHub** [comment]
Nevermind I got it I put the ./lib folder into the ./www folder. (Why didn't I think of this before?)

**Comment by softnya** [comment]
I have a similar issue. I have enable3d with Phaser in a Cordova project, but when I try to load ammo library I have this error:
Uncaught (in promise) RuntimeError: abort(RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info

If I load this on web all is fine, but compiled for mobile is different. I can see that something must be configured, but I don't know what, this is my config file:
	const config = {
		width: 1920,
		height: 1080,
        type: Phaser.WEBGL,
        transparent: true,
		title: ""),
		version: "0.13.10",
		physics: {
			default: "arcade",
			arcade: {
				debug: false,
				Gravity: { y: 400 }
			}
		},
        scale: {
          mode: Phaser.Scale.FIT,
          autoCenter: Phaser.Scale.CENTER_BOTH,
        },
		pixelArt: true,
		roundPixels: true
        scene: [Boot],
        //...Canvas()
	};
	enable3d(() => new Phaser.Game(config)).withPhysics('lib/3d/ammo/kripken');

**Comment by yandeu** [comment]
I just found this https://studiolacosanostra.github.io/2020/02/23/How-to-run-rust-wasm-on-cordova/.

Maybe try to preload ammo.js via `new XMLHttpRequest()`
